
module.exports = {
  STRAVA_CLIENT_ID: process.env.STRAVA_CLIENT_ID,
  STRAVA_CLIENT_SECRET: process.env.STRAVA_CLIENT_SECRET,
  SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
  SPOTIFY_AUTHORIZATION: process.env.SPOTIFY_AUTHORIZATION,
  DARKSKY_KEY: process.env.DARKSKY_KEY,
  DATABASE_URL: process.env.DATABASE_URL,
  PORT: process.env.PORT
};
