import React from 'react';
import Page from './Page';

const dummyText = 'Lorem ipsum dolor sit amet, in suspendisse elementum quis nullam curabitur, sodales ac eu vehicula condimentum. In magnis a orci vel maecenas sed. Nascetur ante consectetuer taciti condimentum. Sagittis ut risus, eget tempus arcu montes sollicitudin suspendisse vitae, commodi mauris pulvinar. Ac pede suscipit integer natoque duis ligula, suspendisse amet, consectetuer nullam vitae, ac duis quis commodo. Nisl at rhoncus, mauris pellentesque lobortis nec, quam eget ligula faucibus nonummy, est tortor lacus magna. Maecenas magna turpis ac id, lacus urna, in ornare. Quam tempor, primis in ut. Ultricies egestas ipsum, ante hymenaeos ullamcorper corporis orci, at quis vehicula placeat sollicitudin metus tristique. Suscipit neque iaculis justo nascetur nulla amet, ac feugiat lectus tortor tellus nullam luctus, phasellus porttitor sit vel. In orci sit et, sagittis ridiculus sed in wisi aliquam senectus. Aspernatur lorem ultrices ut, nibh ac mauris arcu, wisi sollicitudin vestibulum nam massa. Nascetur malesuada libero id id amet, nec pede litora, est ullamcorper magna, morbi et lacinia, at sollicitudin amet. Etiam aenean arcu est qui, dolor molestie, libero iaculis ut. Justo est cras et, pellentesque id quis odio id placerat, quam pede, ipsum pellentesque maecenas id nec sed, proin wisi sed ornare ac tristique. Non sagittis pede vitae quam maecenas pulvinar. Odio posuere metus praesent ut, ac varius magna nibh urna quis mauris. Donec amet vitae metus aliquam libero fermentum, amet ornare morbi sem, erat vitae eget consectetuer. Tortor a, leo urna dui dolor egestas cum, aenean rutrum nec. Fringilla eu neque pharetra pellentesque lectus nulla, tempus wisi ultricies sagittis fusce est, eu egestas nulla at, in pretium iaculis. Augue feugiat, bibendum magna sagittis tristique. Enim sed magna in fusce cras, pulvinar ante aliquam lacus nulla, malesuada feugiat amet luctus adipiscing arcu vitae. Neque lacus eget, interdum pellentesque lobortis, ut aenean, class dolor habitant laoreet integer et ipsum, sit a nullam duis vel viverra. Massa lorem laoreet est tincidunt nunc, hac sunt metus. Suscipit nulla erat orci pellentesque, fugit lacinia at erat ut, varius tristique egestas commodo ut, libero erat amet minim. Nisl et faucibus placerat eget pellentesque mauris, sit sapien at quisque quis ipsum, pede eros aenean, imperdiet in in convallis, ea cras maecenas quis nullam libero. Nibh varius tortor eget. Praesent nullam sem integer integer congue sem, quis ac, vel sollicitudin, quis nulla. Eros sem molestie risus nonummy eu, cras sodales egestas tempus, amet dolor etiam lacinia id dolor, est praesent faucibus.';

const TestPage = ({ athlete }) => (
  <Page athlete={athlete}>
    <p>Hello there</p>
    <p>{dummyText}</p>
  </Page>
);

export default TestPage;
