
export const STRAVA_CLIENT_ID = process.env.REACT_APP_STRAVA_CLIENT_ID;
export const SPOTIFY_CLIENT_ID = process.env.REACT_APP_SPOTIFY_CLIENT_ID;
export const STRAVA_REDIRECT_URI = process.env.REACT_APP_STRAVA_REDIRECT_URI;
export const SPOTIFY_REDIRECT_URI = process.env.REACT_APP_SPOTIFY_REDIRECT_URI;
export const API_URL = process.env.REACT_APP_API_URL;
